language: java
jdk:
- oraclejdk7
sudo: false

# script for build and release via Travis to Bintray
script: gradle/buildViaTravis.sh

# cache between builds
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
  
env:
  global:
  - secure: 
  - secure: 
  - secure: 
  - secure: 
