language: groovy
jdk:
- oraclejdk8
sudo: false

# script for build and release via Travis to Bintray
script: gradle/buildViaTravis.sh

# cache between builds
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
  
env:
  global:
  - secure: viivzqHmn0SdcsxrZnWfmXzYkLE/SxvGvrZErZea0xOpSunMisLwA5WAYN3KZEbp2oXcRW5+68VaFK0tjZtD6hsay9q6gtofqhiamHig5yWR9+HsR2veMN/BPCtka5lOKSNlw0JtbH4aoK15nTJh2evddT+WIFmVj5JInO79UjsIGa4vB+62vJFe/n+m441U5ToM3gZltTD/+gGpHJqP71whSqYpg9eUVOXhGY/s9QdGbURiCpnrx0zcw4WMGolrfXJIVM7D33GqoTBt8ltJLJLhCPIvqT0YNwdcLvN0LdAErAi6rGVRLIdJ732+lqvgThc65y5uSY7KfMd/5hDKg13RFS0vPauUZXj1PK9Rjy04zq4Tr7ZMpU9hPnpR2294mTWsO624URVjBVJIkGftg0whmenfZuFgakujEE4ZofON+dGwErthRV0ZgvBaCS/Luu9Iph08h18Dpww4DSzI0RixprI60fiaPAVqVZzKeoXFS58JC/gK0YtYlbPee/D+qM7n/hCGA0NNCTL5wj+FUi7Yn/TpdyaY/47q+DEGzjMKH+ppFULRwdFJmPAwcpaX357SQudjiODpjpSuKy6MXVt/sEug3c5z9n19NOfZeitWTTutxCwynqx9+gv8eKyYT3X5uaA1eta5CzLGK566ga7eY/AUrbOcwt4HogEq9b8=
  - secure: uA65PLULKgdYf/OEcJ5EdUMPTppl5caLpSyE2DQZe7h2XBJ0ocN8kS70j3VA6ER1EAVV9zWIE15Ib4GrCSdMJll+PFj7iGbVFhaNG5zMygJMlW9NN04ra6hFzQ4lsS75xkupDzwY+dJN7UOa2Jv07NietKUlIqIi57ohCUuQnginV+d7jTUIcab4KnkjcXhbAGOYhvBMnhjr6fdof1vO2fgWtvFKhoSN+1Ob2mCO9aGnsYumNBWhZTGZiagN6ztVsKaZG4vrpMtBy9vOMVMna7uCf1vvLqL5iSQ4Cf6+lkhreLnRdJNr9fOQTgrfsMsOJdy73T5F1pM1t1kNeIo8kH6oXrvth3Jb+II0FfroLP2lC9ZeyKj0logdVdEmMQdP+x3M4AoCIk6pAYfQBAP2zPblpTGL+Y1eVd/dHfSLd3faoiaWD2ZCp9JqZq9hDrCgEtiBZ6FBk40/DQTjqpMeadUoAZFrkCFLPlRaB+5HplgMtfzEnacnJj+K1WrROclAfYVC9f0ywcQxwphFP1DzxyDsIA5t7b64LlYOnf16vlAOdRFxGoJ8U8+7xpZ1YwAljOqrXDW/xVK151vzTEoLZusisK0AfXwbkr7JjEMRg2Oh0QS6OdisBhXloeuMsp71Nea+uVQr9h1hGFo0xHEu21zQdTg8fYQXBYXSezYQssA=